
// Objective-C API for talking to the following Go packages
//
//	coingrig.com/addr
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Addr_FRAMEWORK_H__
#define __Addr_FRAMEWORK_H__

#include "Addr.objc.h"
#include "Universe.objc.h"

#endif
