// Objective-C API for talking to coingrig.com/addr Go package.
//   gobind -lang=objc coingrig.com/addr
//
// File is generated by gobind. Do not edit.

#ifndef __Addr_H__
#define __Addr_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class AddrWallet;

@interface AddrWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull privateKey;
@end

FOUNDATION_EXPORT NSString* _Nonnull AddrGenerateMnemonic(long size);

FOUNDATION_EXPORT NSString* _Nonnull AddrGenerateWallet(NSString* _Nullable mnemonic, NSString* _Nullable chain, NSError* _Nullable* _Nullable error);

#endif
