
// Objective-C API for talking to the following Go packages
//
//	github.com/coingrig/coingrig-go-wallet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __CGWallet_FRAMEWORK_H__
#define __CGWallet_FRAMEWORK_H__

#include "CGWallet.objc.h"
#include "Universe.objc.h"

#endif
