// Objective-C API for talking to github.com/coingrig/gocore Go package.
//   gobind -lang=objc github.com/coingrig/gocore
//
// File is generated by gobind. Do not edit.

#ifndef __CGWallet_H__
#define __CGWallet_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CGWalletWallet;

@interface CGWalletWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull address;
@property (nonatomic) NSString* _Nonnull privateKey;
@end

FOUNDATION_EXPORT NSString* _Nonnull CGWalletGenerateMnemonic(long size);

FOUNDATION_EXPORT NSString* _Nonnull CGWalletGenerateWallet(NSString* _Nullable mnemonic, NSString* _Nullable chain, NSError* _Nullable* _Nullable error);

#endif
