require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
# install! 'cocoapods',
#          :deterministic_uuids => false
target 'WalletGeneratorExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'coingrig-wallet-generator', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

end
